expressions main 1
expr 1 30

eval_ae_sets main 11
eval_ae 0 0
eval_ae 1 0
eval_ae 2 0
eval_ae 3 0
eval_ae 4 0
eval_ae 5 0
eval_ae 6 0
eval_ae 7 0
eval_ae 8 0
eval_ae 9 1
eval_ae 10 0

kill_ae_sets main 11
kill_ae 0 0
kill_ae 1 1
kill_ae 2 0
kill_ae 3 0
kill_ae 4 1
kill_ae 5 0
kill_ae 6 0
kill_ae 7 1
kill_ae 8 0
kill_ae 9 0
kill_ae 10 0

available_exprs main 11
avail_exprs_out 0 0
avail_exprs_out 1 0
avail_exprs_out 2 0
avail_exprs_out 3 0
avail_exprs_out 4 0
avail_exprs_out 5 0
avail_exprs_out 6 0
avail_exprs_out 7 0
avail_exprs_out 8 0
avail_exprs_out 9 1
avail_exprs_out 10 1

